ERP_System/urls.py
from django.contrib import admin
from django.urls import path, include
from admin_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('adminuser/',include('admin_app.urls')),
    path('user/',include('user_app.urls')),
]

admin_app/urls.py
from django.urls import path
from . import views

app_name = 'admin_app'

urlpatterns = [
    path('login/',views.loginadmin,name='login'),
    path('logout/',views.logout,name='logout'),
    path('dashboard',views.admindashboard,name='admindashboard'),
    path('upload/',views.upload),
    path('download/',views.download),
    path('textfile/',views.downloadtextfile,name='downloadtextfile'),
    path('pdffile/', views.downloadpdffile, name='downloadpdffile'),
    path('generatepdf/', views.generatepdf, name='generatepdf'),

]

user_app/urls.py
from django.urls import path
from . import views

app_name = 'user_app'

urlpatterns = [
    path('login/',views.loginuser,name='loginuser'),
    path('registartion/', views.registration, name='registration'),
    path('after_registration',views.after_registration,name='after_registration'),
    path('dashboard', views.userdashboard, name='userdashboard'),

]

admin_app/models.py
from django.db import models

class Admin(models.Model):
    admin_email = models.CharField(max_length=200)
    admin_password = models.CharField(max_length=200)

user_app/models.py
from django.db import models

class UserData(models.Model):
    full_name = models.CharField(max_length=200)
    dob = models.DateField(max_length=8)
    salary = models.IntegerField()
    country = models.CharField(max_length=20)
    email = models.CharField(max_length=40)
    password = models.CharField(max_length=200)

admin_app/views.py
from django.shortcuts import render, redirect
from . import models
from user_app.models import UserData
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
from reportlab.pdfgen import canvas

# Create your views here.


def index(request):
    return render(request,'admin_app/index.html')


def loginadmin(request):
    return render(request,'admin_app/loginadmin.html')

def set_session(request,uname,pwd):
    if uname!="" and pwd != "":
        request.session['usernam'] = uname
        request.session['passowrd'] = pwd
        return  True
    else:
        return False



def admindashboard(request):
    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('pass')
        request.session['username'] = email
        request.session['password'] = password
        if request.session.has_key('username') and request.session.has_key('password'):
            if models.Admin.objects.filter(admin_email=request.session['username'], admin_password=request.session['password']):
                # request.session.set_expiry(30)
                user_list = UserData.objects.order_by('full_name')
                user_dict = {'users':user_list}
                return render(request,'admin_app/admin_dashboard.html',context=user_dict)
            else:
                return HttpResponse("ok")
    else:
        return HttpResponse("<html><body><h1 align='center' style='color:red'>OOPS! Incorrect username or password </h1></body></html>")

def logout(request):
    try:
        del request.session['username']
    except:
        pass
    return redirect('/')


def upload(request):
    folder = '/uploadedfile'
    file = request.FILES['myfile']
    fs = FileSystemStorage(location=folder)
    filename = fs.save(file.name,file)
    file_url = fs.url(filename)
    return render(request,'admin_app/upload.html',{'file_url': file_url})

def download(request):
    return render(request,'admin_app/download.html')

def downloadtextfile(request):
    with open("./files/InterviewRelated",'rb') as file:
        response = HttpResponse(file.read(),content_type='text/plain')
        response['Content-Disposition'] = 'inline;filename=download.txt'
        return response
def downloadpdffile(request):
    with open("./files/Nikhil_Jain_Resume.pdf",'rb') as file:
        response = HttpResponse(file.read(),content_type='application/pdf')
        response['Content-Disposition'] = 'attachement;filename=download.pdf'
        return response

def generatepdf(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'inline;filename=somefilename.pdf'
    p = canvas.Canvas(response)
    p.drawString(100,100,"Hello World")
    p.showPage()
    p.save()
    return response

user_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import models
# Create your views here.

temp = 0

def loginuser(request):
    return render(request,'user_app/loginuser.html')

def registration(request):
    return render(request, 'user_app/registration.html')

def after_registration(request):
    full_name = request.POST.get('name')
    dob = request.POST.get('dob')
    salary = request.POST.get('salary')
    country = request.POST.get('country')
    email = request.POST.get('email')
    password = request.POST.get('pass')

    data = models.UserData(full_name = full_name, dob = dob, salary = salary, country = country, email = email, password = password)
    data.save()

    return render(request,'user_app/after_registration.html')

def userdashboard(request):
    email = request.POST.get('email')
    password = request.POST.get('pass')
    password = request.POST.get('pass')
    if models.UserData.objects.filter(email=email, password=password):
        request.session['username'] = password;
        return render(request, 'user_app/user_dashboard.html')
    else:
        return HttpResponse(
            "<html><body><h1 align='center' style='color:red'>OOPS! Incorrect username or password </h1></body></html>")


def logout(request):
    try:
        del request.session['username']
    except:
        pass
    return redirect('/')

templates/admin_app/admin_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }

        td, th {
          border: 1px solid #dddddd;
          text-align: left;
          padding: 8px;
        }

        tr:nth-child(even) {
          background-color: #dddddd;
        }
    </style>

</head>

<body>
    <div>
        <h1>Succefully login in admin dashboard</h1>
        <div style="float:right;font-size:20px;">
          <a href="{% url 'admin_app:logout' %}">Logout</a>
        </div>
    </div>
    <h2 align="center">User Data</h2>
    <table>
      <tr>
          <th></th>
          <th>Name</th>
          <th>DOB</th>
          <th>Country</th>
          <th>Email</th>
          <th>Salary</th>
      </tr>
      {% if users %}
      {% for user in users %}
      <tr>
          <div id="checkboxes">
              <td><input type="checkbox" class="radio"/></td></div>
          <td>{{user.full_name}}</td>
          <td>{{user.dob}}</td>
          <td>{{user.country}}</td>
          <td>{{user.email}}</td>
          <td>{{user.salary}}</td>
      </tr>
      {% endfor %}
      {% else %}
        <span style="color:red;">No data</span>
      {% endif %}
    </table>
    <input type="submit" name="modifyData" class="button" id ="modifyData" value=" Modify " />
    <input type="submit" name="addData" class="button" id ="addData" value=" Add " />
    <input type="submit" name="deleteData" class="button" id ="deleteData" value=" Delete " />

</body>
</html>

templates/admin_app/download.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <a href="{% url 'admin_app:downloadtextfile' %}">Text File</a><br><br>
    <a href="{% url 'admin_app:downloadpdffile' %}">pdf File</a><br><br>
    <a href="{% url 'admin_app:generatepdf' %}">Generate PDF</a><br><br>
</body>
</html>

templates/admin_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <style>

        .div1{
             padding : 20px;
             margin-left : 30px;
             background-color:#91949212;
             width: 30%;
             float:left
         }
         a{
            text-decoration:none;
            font-size:20px;

         }
    </style>
</head>
<body>
    <div class="div1">
        <a href="{% url 'admin_app:login' %}">Admin</a>
        <a href="{% url 'user_app:loginuser' %}">User</a>
    </div>
</body>
</html>

templates/admin_app/loginadmin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin Login</title>
    <style>

        body{
          font-family: 'Open Sans', sans-serif;
          background:#547992;
          margin: 0 auto 0 auto;
          width:100%;
          text-align:center;
          margin: 20px 0px 20px 0px;
        }

        p{
          font-size:12px;
          text-decoration: none;
          color:#ffffff;
        }

        h1{
          font-size:1.5em;
          color:#525252;
        }

        .box{
          background:white;
          width:300px;
          border-radius:6px;
          margin: 0 auto 0 auto;
          padding:0px 0px 70px 0px;
          border: #2980b9 4px solid;
        }

        .email{
          background:#ecf0f1;
          border: #ccc 1px solid;
          border-bottom: #ccc 2px solid;
          padding: 8px;
          width:250px;
          color:black;
          margin-top:10px;
          font-size:1em;
          border-radius:4px;
        }

        .password{
          border-radius:4px;
          background:#ecf0f1;
          border: #ccc 1px solid;
          padding: 8px;
          width:250px;
          font-size:1em;
        }

        .btn{
          background:#2ecc71;
          width:125px;
          padding-top:5px;
          padding-bottom:5px;
          color:white;
          border-radius:4px;
          border: #27ae60 1px solid;

          margin-top:20px;
          margin-bottom:20px;
          float:left;
          margin-left:77px;
          font-weight:800;
          font-size:0.8em;
        }

        .btn:hover{
          background:#2CC06B;
        }

    </style>
</head>
<body>
    <form method="post" action="/adminuser/dashboard">
        {% csrf_token %}
        <div class="box">
            <h1>Admin Login</h1>

            <input type="email" name="email" placeholder="Email" class="email" required/>

            <input type="password" name="pass" placeholder="password" class="email" required/>

            <input type="submit" class="btn" value="Sign In"/> <!-- End Btn -->

        </div> <!-- End Box -->

    </form>


</body>
</html>

templates/admin_app/upload.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
 <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile"/>
 </form>
</body>
</html>

templates/user_app/after_registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Successfully Login</h1>
    <h1>Go to the <a href="{% url 'user_app:loginuser' %}">User Login</a>Page</h1>
</body>
</html>

templates/user_app/loginuser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Login</title>
<style>

        body{
          font-family: 'Open Sans', sans-serif;
          background:#547992;
          margin: 0 auto 0 auto;
          width:100%;
          text-align:center;
          margin: 20px 0px 20px 0px;
        }

        p{
          font-size:12px;
          text-decoration: none;
          color:#ffffff;
        }

        h1{
          font-size:1.5em;
          color:#525252;
        }

        .box{
          background:white;
          width:300px;
          border-radius:6px;
          margin: 0 auto 0 auto;
          padding:0px 0px 70px 0px;
          border: #2980b9 4px solid;
        }

        .email{
          background:#ecf0f1;
          border: #ccc 1px solid;
          border-bottom: #ccc 2px solid;
          padding: 8px;
          width:250px;
          color:black;
          margin-top:10px;
          font-size:1em;
          border-radius:4px;
        }

        .password{
          border-radius:4px;
          background:#ecf0f1;
          border: #ccc 1px solid;
          padding: 8px;
          width:250px;
          font-size:1em;
        }

        .btn{
          background:#2ecc71;
          width:125px;
          padding-top:5px;
          padding-bottom:5px;
          color:white;
          border-radius:4px;
          border: #27ae60 1px solid;

          margin-top:20px;
          margin-bottom:20px;
          float:left;
          margin-left:16px;
          font-weight:800;
          font-size:0.8em;
        }

        .btn:hover{
          background:#2CC06B;
        }

        #btn2{
          float:left;
          background:#3498db;
          width:125px;  padding-top:5px;
          padding-bottom:5px;
          color:white;
          border-radius:4px;
          border: #2980b9 1px solid;

          margin-top:20px;
          margin-bottom:20px;
          margin-left:10px;
          font-weight:800;
          font-size:0.8em;
        }

        #btn2:hover{
        background:#3594D2;
        }
    </style>
</head>
<body>
    <form method="post" action="/user/dashboard">
        {% csrf_token %}
        <div class="box">
        <h1>User Login</h1>

        <input type="email" name="email" placeholder="Email" onFocus="field_focus(this, 'email');" onblur="field_blur(this, 'email');" class="email" required />

        <input type="password" name="pass" placeholder="Password" onFocus="field_focus(this, 'email');" onblur="field_blur(this, 'email');" class="email" required/>

        <input type="submit" class="btn" value="Sign In"/>
        <a href="{% url 'user_app:registration' %}"><div id="btn2">Sign Up</div></a>

        </div> <!-- End Box -->

    </form>

<p>Forgot your password? <u style="color:#f1c40f;">Click Here!</u></p>

</body>

templates/user_app/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Login</title>
<style>

        body{
          font-family: 'Open Sans', sans-serif;
          background:#547992;
          margin: 0 auto 0 auto;
          width:100%;
          text-align:center;
          margin: 20px 0px 20px 0px;
        }

        p{
          font-size:12px;
          text-decoration: none;
          color:#ffffff;
        }

        h1{
          font-size:1.5em;
          color:#525252;
        }

        .box{
          background:white;
          width:300px;
          border-radius:6px;
          margin: 0 auto 0 auto;
          padding:0px 0px 70px 0px;
          border: #2980b9 4px solid;
        }

        .reg{
          background:#ecf0f1;
          border: #ccc 1px solid;
          border-bottom: #ccc 2px solid;
          padding: 8px;
          width:250px;
          color:black;
          margin-top:10px;
          font-size:1em;
          border-radius:4px;
        }

        .password{
          border-radius:4px;
          background:#ecf0f1;
          border: #ccc 1px solid;
          padding: 8px;
          width:250px;
          font-size:1em;
        }

        .btn{
          background:#2ecc71;
          width:125px;
          padding-top:5px;
          padding-bottom:5px;
          color:white;
          border-radius:4px;
          border: #27ae60 1px solid;

          margin-top:20px;
          margin-bottom:20px;
          float:left;
          margin-left:77px;
          font-weight:800;
          font-size:0.8em;
        }

        .btn:hover{
          background:#2CC06B;
        }

        #btn2{
          float:left;
          background:#3498db;
          width:125px;  padding-top:5px;
          padding-bottom:5px;
          color:white;
          border-radius:4px;
          border: #2980b9 1px solid;

          margin-top:20px;
          margin-bottom:20px;
          margin-left:10px;
          font-weight:800;
          font-size:0.8em;
        }

        #btn2:hover{
        background:#3594D2;
        }
    </style>
</head>
<body>
    <form method="post" action="/user/after_registration">
        {% csrf_token %}
        <div class="box">
            <h1>User Registration</h1>
            <input type="text" name="name" placeholder="Full Name" class="reg" required/>

            <input  type="text" name="dob" placeholder="dateofbirth" class="reg" required/>

            <input type="text" name="salary" placeholder="Salary" class="reg" required/>

            <input type="text" name="country" placeholder="Country" class="reg" required/>

            <input type="email" name="email" placeholder="Email" class="reg" required/>

            <input type="password" name="pass" placeholder="Password" class="reg" required/>

            <input type="submit" class="btn" value="Submit"/>

        </div> <!-- End Box -->

    </form>


</body>

templates/user_app/user_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Succefully login in user dashboard</h1>
</body>
</html>